-- MySQL Script generated by MySQL Workbench
-- Wed Mar  8 15:36:56 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema wordgames
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `wordgames` ;

-- -----------------------------------------------------
-- Schema wordgames
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `wordgames` DEFAULT CHARACTER SET utf8 ;
USE `wordgames` ;

-- -----------------------------------------------------
-- Table `wordgames`.`equipo`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `wordgames`.`equipo` ;

CREATE TABLE IF NOT EXISTS `wordgames`.`equipo` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(100) NOT NULL,
  `puntos` INT NOT NULL,
  `logo` VARCHAR(100) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `idEquipo_UNIQUE` (`id` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `wordgames`.`jugador`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `wordgames`.`jugador` ;

CREATE TABLE IF NOT EXISTS `wordgames`.`jugador` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `admin` INT NOT NULL,
  `nombre` VARCHAR(45) NOT NULL,
  `clave` VARCHAR(100) NOT NULL,
  `avatar` VARCHAR(100) NULL DEFAULT NULL,
  `puntos` INT NULL DEFAULT NULL,
  `equipo_id` INT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `idJugador_UNIQUE` (`id` ASC) VISIBLE,
  INDEX `fk_Jugador_Equipo1_idx` (`equipo_id` ASC) VISIBLE,
  CONSTRAINT `fk_Jugador_Equipo1`
    FOREIGN KEY (`equipo_id`)
    REFERENCES `wordgames`.`equipo` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `wordgames`.`juego`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `wordgames`.`juego` ;

CREATE TABLE IF NOT EXISTS `wordgames`.`juego` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `dificultad` VARCHAR(45) NOT NULL,
  `nombre` VARCHAR(100) NOT NULL,
  `instrucciones` VARCHAR(500) NOT NULL,
  `intentosMax` INT NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `wordgames`.`partida`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `wordgames`.`partida` ;

CREATE TABLE IF NOT EXISTS `wordgames`.`partida` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `jugador_id` INT NOT NULL,
  `juego_id` INT NOT NULL,
  `date` DATETIME NOT NULL,
  `puntos` INT NOT NULL,
  `palabra` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`, `jugador_id`, `juego_id`),
  INDEX `fk_Jugador_has_Juego_Juego1_idx` (`juego_id` ASC) VISIBLE,
  INDEX `fk_Jugador_has_Juego_Jugador_idx` (`jugador_id` ASC) VISIBLE,
  CONSTRAINT `fk_Jugador_has_Juego_Jugador`
    FOREIGN KEY (`jugador_id`)
    REFERENCES `wordgames`.`jugador` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Jugador_has_Juego_Juego1`
    FOREIGN KEY (`juego_id`)
    REFERENCES `wordgames`.`juego` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
